// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRecentProject'](arg1, arg2, arg3);
}

export function DetectPortsWithInfo() {
  return window['go']['main']['App']['DetectPortsWithInfo']();
}

export function DetectRunningPorts() {
  return window['go']['main']['App']['DetectRunningPorts']();
}

export function GetProjectInfo() {
  return window['go']['main']['App']['GetProjectInfo']();
}

export function GetProxyURL() {
  return window['go']['main']['App']['GetProxyURL']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenRecentProject(arg1, arg2) {
  return window['go']['main']['App']['OpenRecentProject'](arg1, arg2);
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
