// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {config} from '../models';

export function AddRecentProject(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DetectPortsWithInfo():Promise<Array<proxy.PortInfo>>;

export function DetectRunningPorts():Promise<Array<number>>;

export function GetProjectInfo():Promise<Record<string, any>>;

export function GetProxyURL():Promise<string>;

export function GetRecentProjects():Promise<Array<config.RecentProject>>;

export function GetStatus():Promise<Record<string, any>>;

export function OpenRecentProject(arg1:string,arg2:number):Promise<string>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function SelectProjectDirectory():Promise<string>;

export function SetAPIKey(arg1:string):Promise<void>;

export function StartProxy(arg1:string,arg2:number):Promise<string>;

export function StopProxy():Promise<string>;
